version: 0.2

phases:
  pre_build:
    commands:
      # Log in to Amazon ECR
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${account_id}.dkr.ecr.us-east-2.amazonaws.com
      
  build:
    commands:
      # Build the Docker image
      - docker build -t ecsflaskapp .

  post_build:
    commands:
      # Push the Docker image to Amazon ECR
      - docker tag ecsflaskapp ${account_id}.dkr.ecr.us-east-2.amazonaws.com/ecs-flaskapp:${CODEBUILD_RESOLVED_SOURCE_VERSION}-v${CODEBUILD_BUILD_NUMBER}
      - docker push ${account_id}.dkr.ecr.us-east-2.amazonaws.com/ecs-flaskapp:${CODEBUILD_RESOLVED_SOURCE_VERSION}-v${CODEBUILD_BUILD_NUMBER}
      - aws ecs update-service --cluster ECS-Cluster-FlaskApp --service ECS-Service --force-new-deployment

artifacts:
  files:
    # You don't need any artifacts, so we leave this section empty
  discard-paths: yes
